name: hugo-book auto build 

on:
  push:
    branches:
      - master
      - main
  # schedule:
  #   #  UTC 16:00 -> CST 00:00
  #   # - cron: "10 17 * * *"  # UTC 17:00 -> CST 01:00 (day+1)
  #   - cron: "10 01 * * *"  # CST with set-timezone

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # # https://github.com/szenius/set-timezone
      # - uses: szenius/set-timezone@v1.0
      #   with:
      #     timezoneLinux: "Asia/Shanghai"

      - uses: actions/checkout@v3
        with:
          submodules: true

      # - name: download tools qcloud-cdn-purge
      #   run: |
      #     make download

      - name: run qcloud-cdn-purge
        run: |
          uname -s
          uname -m
          which wget
          which curl

